### PR TITLE
Fix corner case for empty R_LIBS_USER

### PR DESCRIPTION
**Pull request by krlmlr**
Downstream: https://github.com/rstudio/renv/issues/1020

I don't understand enough about this problem yet, but this change in my local `/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/base/R/Rprofile` fixed the symptoms.

How do I reapply this change to all installations?

### CODE REVIEW

**Comment by gaborcsardi** [comment]
Thanks!

**Comment by gaborcsardi** [comment]
@krlmlr Can you try to reinstall R with https://github.com/r-lib/rig/releases/tag/v0.4.2 ?

**Comment by krlmlr** [comment]
Thanks, will do! When will it be available via Homebrew?

**Comment by gaborcsardi** [comment]
Once it is not a pre-release, yeah.

**Pull request merged**
