### PR TITLE
fix: `--without-sysreqs` works

### LINKED ISSUE #184: `--without-sysreqs` is not working?
```log
#15 70.89 [INFO] Adding /usr/local/bin/R-4.3.1 -> /opt/R/4.3.1/bin/R
#15 70.89 [INFO] Adding R-release alias to R 4.3.1
#15 70.89 [INFO] Setting default CRAN mirror
#15 70.89 [INFO] Setting up P3M
#15 70.89 [INFO] Setting up automatic system requirements installation.
```

I noticed the above log even though I added the `--without-sysreqs` flag in the following location.
https://github.com/rocker-org/devcontainer-features/blob/69598501ac7fc591878b9e29ca8e730768c4fa10/src/r-rig/install.sh#L331

It seems `--without-sysreqs` does nothing?

https://github.com/r-lib/rig/blob/74bb252854431a9630167ad7b6ed2c0b842a0105/src/linux.rs#L609-L633

### PR DESCRIPTION
**Pull request by eitsupi**
Fix #184

### CODE REVIEW

**Comment by eitsupi** [comment]
I'm not sure if this solution is correct.
That is, since `PKG_SYSREQS="false"` is set by Rprofile, the user cannot override this setting and temporarily make `PKG_SYSREQS="false"` available by setting `PKG_SYSREQS` in an environment variable or Renviron, right?

**Comment by gaborcsardi** [comment]
I think it should only set it if it is not already set:
```
if (Sys.getenv("PKG_SYSREQS") != "") Sys.setenv(PKG_SYSREQS = "false")
```

The user or system profile can override it, I think, since it runs after this "internal" profile.

**Comment by gaborcsardi** [comment]
Thanks!

**Comment by gaborcsardi** [comment]
Yes, we'll have one at some point, but a release is quite a lot of work. 

If you need a quick workaround for the current release, you can use `--without-sysreqs` and set up the `PKG_SYSREQS` env var system wide.

Alternatively, for x86_64 Linux you can download a build from a nightly test artifact, e.g. https://github.com/r-lib/rig/actions/runs/6295783883

**Comment by eitsupi** [comment]
I see, thanks for your reply!

**Pull request merged**
